apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-dep-2
spec:
  selector:
    matchLabels:
      app: nginx-2
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx-2
    spec:
      containers:
      - name: nginx-2
        image: nginx:latest
        ports:
        - containerPort: 80     
